---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: R1
  gather_facts: false
  connection: local

  tasks:
    - name: DISPLAYING THE RUNNING-CONFIG
      ios-command:
        commands:
          -show running-config
      register: config

    - name: SAVE OUTPUT TO ./backups/
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "backup/show_run {{ inventory_hostname }}.txt"
